name: Deploy Backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    #########################################
    # Checkout Repo
    #########################################

    - name: Checkout Repository
      uses: actions/checkout@v4

    #########################################
    # Configure AWS using OIDC
    #########################################

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-south-1

    #########################################
    # Setup Terraform
    #########################################

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    #########################################
    # Terraform Init
    #########################################

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    #########################################
    # Terraform Validate
    #########################################

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    #########################################
    # Terraform Apply
    #########################################

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve

    #########################################
    # Get ECR Repo from Terraform Output
    #########################################

    - name: Get ECR Repo
      id: ecr
      working-directory: terraform
      run: |
        REPO=$(terraform output -raw ecr_repo | tr -d '\n')
        echo "repo=$REPO" >> $GITHUB_OUTPUT

    #########################################
    # Login to ECR
    #########################################

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 \
        | docker login \
        --username AWS \
        --password-stdin ${{ steps.ecr.outputs.repo }}

    #########################################
    # Build Docker Image
    #########################################

    - name: Build Docker Image
      run: |
        docker build -t farmer-backend ./backend

    #########################################
    # Tag Docker Image
    #########################################

    - name: Tag Docker Image
      run: |
        docker tag farmer-backend:latest \
        ${{ steps.ecr.outputs.repo }}:latest

    #########################################
    # Push Image to ECR
    #########################################

    - name: Push Image
      run: |
        docker push ${{ steps.ecr.outputs.repo }}:latest

    #########################################
    # Force ECS Rolling Deployment
    #########################################

    - name: Redeploy ECS Service
      run: |
        aws ecs update-service \
          --cluster farmer-cluster \
          --service farmer-backend-service \
          --force-new-deployment